// src/constants/countries.js
export const COUNTRIES = [
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Albania", label: "Albania" },
  { value: "Algeria", label: "Algeria" },
  { value: "Argentina", label: "Argentina" },
  { value: "Armenia", label: "Armenia" },
  { value: "Australia", label: "Úc" },
  { value: "Austria", label: "Áo" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Belarus", label: "Belarus" },
  { value: "Belgium", label: "Bỉ" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Brazil", label: "Brazil" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Cambodia", label: "Campuchia" },
  { value: "Canada", label: "Canada" },
  { value: "Chile", label: "Chile" },
  { value: "China", label: "Trung Quốc" },
  { value: "Colombia", label: "Colombia" },
  { value: "Croatia", label: "Croatia" },
  { value: "Czech Republic", label: "Séc" },
  { value: "Denmark", label: "Đan Mạch" },
  { value: "Egypt", label: "Ai Cập" },
  { value: "Estonia", label: "Estonia" },
  { value: "Finland", label: "Phần Lan" },
  { value: "France", label: "Pháp" },
  { value: "Georgia", label: "Georgia" },
  { value: "Germany", label: "Đức" },
  { value: "Greece", label: "Hy Lạp" },
  { value: "Hong Kong", label: "Hồng Kông" },
  { value: "Hungary", label: "Hungary" },
  { value: "Iceland", label: "Iceland" },
  { value: "India", label: "Ấn Độ" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Iran", label: "Iran" },
  { value: "Iraq", label: "Iraq" },
  { value: "Ireland", label: "Ireland" },
  { value: "Israel", label: "Israel" },
  { value: "Italy", label: "Ý" },
  { value: "Japan", label: "Nhật Bản" },
  { value: "Jordan", label: "Jordan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Latvia", label: "Latvia" },
  { value: "Lebanon", label: "Liban" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Mexico", label: "Mexico" },
  { value: "Netherlands", label: "Hà Lan" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Norway", label: "Na Uy" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Philippines", label: "Philippines" },
  { value: "Poland", label: "Ba Lan" },
  { value: "Portugal", label: "Bồ Đào Nha" },
  { value: "Qatar", label: "Qatar" },
  { value: "Romania", label: "Romania" },
  { value: "Russia", label: "Nga" },
  { value: "Saudi Arabia", label: "Ả Rập Xê Út" },
  { value: "Singapore", label: "Singapore" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "South Africa", label: "Nam Phi" },
  { value: "South Korea", label: "Hàn Quốc" },
  { value: "Spain", label: "Tây Ban Nha" },
  { value: "Sweden", label: "Thụy Điển" },
  { value: "Switzerland", label: "Thụy Sĩ" },
  { value: "Taiwan", label: "Đài Loan" },
  { value: "Thailand", label: "Thái Lan" },
  { value: "Turkey", label: "Thổ Nhĩ Kỳ" },
  { value: "Ukraine", label: "Ukraina" },
  { value: "United Arab Emirates", label: "UAE" },
  { value: "United Kingdom", label: "Anh" },
  { value: "United States", label: "Mỹ" },
  { value: "Vietnam", label: "Việt Nam" },
];
