const GENRES = [
  "Anime",
  "Ẩm Thực",
  "Bí Ẩn",
  "Chiến Tranh",
  "Chiếu Rạp",
  "Chuyển Thể",
  "Chính Kịch",
  "Chính Luận",
  "Chính Trị",
  "Chương Trình Truyền Hình",
  "Cung Đấu",
  "Cuối Tuần",
  "Cách Mạng",
  "Cổ Trang",
  "Cổ Tích",
  "Cổ Điển",
  "DC",
  "Disney",
  "Đau Thương",
  "Gia Đình",
  "Giáng Sinh",
  "Giả Tưởng",
  "Hoàng Cung",
  "Hoạt Hình",
  "Hài",
  "Hành Động",
  "Hình Sự",
  "Học Đường",
  "Khoa Học",
  "Kinh Dị",
  "Kinh Điển",
  "Kịch Nói",
  "Kỳ Ảo",
  "LGBT+",
  "Live Action",
  "Lãng Mạn",
  "Lịch Sử",
  "Marvel",
  "Miền Viễn Tây",
  "Nghề Nghiệp",
  "Người Mẫu",
  "Nhạc Kịch",
  "Phiêu Lưu",
  "Phép Thuật",
  "Siêu Anh Hùng",
  "Thiếu Nhi",
  "Thần Thoại",
  "Thể Thao",
  "Truyền Hình Thực Tế",
  "Tuổi Trẻ",
  "Tài Liệu",
  "Tâm Lý",
  "Tình Cảm",
  "Tập Luyện",
  "Viễn Tưởng",
  "Võ Thuật",
  "Xuyên Không",
  "Đời Thường"
];
export default GENRES;